import localFont from "next/font/local";
import "./globals.css";
import { Sidebar } from "./components/Sidebar/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex flex-col w-full h-screen">
            <div className="h-20 w-full bg-[#67e6dc] flex items-center justify-center text-5xl font-bold ">STOCK MASTER</div>
            <div className=" w-full h-[calc(100vh-80px)] flex flex-row">
              <Sidebar/>
              {children}
            </div>
          </div>
      </body>
    </html>
  );
}
